[build]
    functions = "dist-functions"

[[redirects]]
    from = "/api/*"
    to = "/.netlify/functions/:splat"
    status = 200

# [context.production.environment]
#   TOML_ENV_VAR = "From netlify.toml"
#   REACT_APP_VAR = "From netlify.toml (REACT_APP_)"